MyWebsite/MyWebsite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include(('article.urls', 'article'), namespace='article')),
    path('userprofile/', include(('userprofile.urls', 'userprofile'), namespace='userprofile')),
    path('password-reset', include('password_reset.urls')),
    path('comment/', include(('comment.urls', 'comment'), namespace='comment')),
]

# 为上传的图片配置URL路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyWebsite/article/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.articled_create, name='article_create'),
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    # 安全删除文章
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

MyWebsite/userprofile/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('logout/', views.uesr_logout, name='logout'),
	path('register/', views.user_register, name='register'),
	path('delete/<int:id>/', views.user_delete, name='delete'),
	# 编辑用户信息
	path('edit/<int:id>/', views.profile_edit, name='edit'),
]

MyWebsite/userprofile/models.py
from django.contrib.auth.models import User
from django.db import models

# 用户扩展信息
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    # 与Users模型构成一对一的关系
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    # 电话号码字段
    phone = models.CharField(max_length=20, blank=True)
    # 头像,ImageField不存储图片，只存储图片地址
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)
    # 个人简介
    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)


'''
在后台中创建并保存User时调用了信号接收函数，创建了Profile表；
但如果此时管理员填写了内联的Profile表，会导致此表也会被创建并保存。
最终结果就是同时创建了两个具有相同User的Profile表，违背了”一对一“外键的原则。
# 信号接收函数，每当更新User实例时自动调用
# post_save是一个内置信号，可以在模型调用save()方法后发出信号
# 信号接收函数，每当新建User实例时自动调用
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()
'''

MyWebsite/userprofile/forms.py
# 登录表单，继承了forms.Form类
from django import forms

# 用户登录
from django.contrib.auth.models import User

from userprofile.models import Profile


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


# 注册用户表单
class UserRegisterForm(forms.ModelForm):
    # 复写User的密码
    password = forms.CharField()
    password2 = forms.CharField()

    # 覆写某字段之后，内部类class Meta中的定义对这个字段就没有效果了，所以fields不用包含password
    class Meta:
        model = User
        fields = ('username', 'email')

    # 对两次输入的密码是否一致进行检查
    # def clean_[字段]这种写法Django会自动调用，来对单个字段的数据进行验证清洗。
    def clean_password2(self):
        data = self.cleaned_data
        # 从POST中取值data.get('password')和data['password']区别
        # 前者即使为空也不会导致程序错误，后者为空时如果data中不包含password会报错
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError('密码输入不一致，请重试！')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', 'avatar', 'bio')

MyWebsite/userprofile/views.py
from django.contrib.auth import authenticate, login, logout
# 引入验证登录的装饰器
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from userprofile.forms import UserLoginForm, UserRegisterForm, ProfileForm

# 用户登录
from userprofile.models import Profile


def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            # .cleaned_data 清洗出合法数据
            data = user_login_form.cleaned_data
            # 检验帐号密码是否匹配数据库中的某个用户
            # 如果均匹配则返回这个user对象
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                # 将用户数据保存在session中，即实现了登陆操作
                login(request, user)
                return redirect('article:article_list')
            else:
                return HttpResponse('帐号或密码输入错误，请重新输入！')
        else:
            # return HttpResponse('error:{} 帐号或密码输入不合法'.format(user_login_form.errors))
            return HttpResponse('帐号或密码输入不合法')
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = {
            'form': user_login_form,
        }
        # print(context)
        return render(request, 'userprofile/login.html', context)
    else:
        return HttpResponse('请使用GET/POST请求数据')


# 用户退出
def uesr_logout(request):
    logout(request)
    return redirect('article:article_list')


# 用户注册
def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            # 设置密码
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            # 保存好数据后立即登录并返回博客界面
            login(request, new_user)
            return redirect('article:article_list')
        else:
            return HttpResponse('注册表单输入有误，请重新输入！！！')
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = {
            'form': user_register_form,
        }
        return render(request, 'userprofile/register.html', context)
    else:
        return HttpResponse('请使用GET/POST方式访问')


# 删除用户（后续修改为逻辑删除）
# @login_required是一个装饰器。装饰器可以在不改变函数内容的前提下，给这个函数添加一些功能
# @login_required要求调用user_delete函数时，用户必须登录；
# 如果未登录则不执行函数，将页面重定向到login_url的地址
@login_required(login_url='userprofile/login/')
def user_delete(request, id):
    if request.method == 'POST':
        user = User.objects.get(id=id)
        # 验证登陆用户、待删除用户是否相同
        if request.user == user:
            # 退出登录，删除数据并返回博客列表
            # 日后进行修改，变成逻辑删除
            logout(request)
            user.delete()
            return redirect('article:article_list')
        else:
            return HttpResponse('你没有删除操作的权限')
    else:
        return HttpResponse('仅接受POST请求')


# 编辑用户信息
@login_required(login_url='/userprofile/login/')
def profile_edit(request, id):
    user = User.objects.get(id=id)
    # user_id是 OneToOneField自动生成的字段
    # Profile已经存在就获取它，不存在则创建一个新的
    if Profile.objects.filter(user_id=id).exists():
        profile = Profile.objects.get(user_id=id)
    else:
        profile = Profile.objects.create(user=user)

    if request.method == 'POST':
        # 验证是否是本人
        if request.user != user:
            return HttpResponse("你没有权限修改该用户信息！")

        profile_form = ProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            # 取得清洗后的合法数据
            profile_cd = profile_form.cleaned_data
            profile.phone = profile_cd.get('phone')
            profile.bio = profile_cd.get('bio')
            # 对文件的特殊处理
            if 'avatar' in request.FILES:
                profile.avatar = profile_cd.get('avatar')
            profile.save()
            # 带参数的redirect()
            return redirect('userprofile:edit', id=id)
        else:
            return HttpResponse('注册表单输入有误，请重新输入')

    elif request.method == 'GET':
        profile_form = ProfileForm()
        '''
        实际上GET方法中不需要将profile_form这个表单对象传递到模板中去，
        因为模板中已经用Bootstrap写好了表单，所以profile_form并没有用到
        '''
        context = {
            'profile_form': profile_form,
            'profile': profile,
            'user': user,
        }
        return render(request, 'userprofile/edit.html', context)
    else:
        return HttpResponse("请使用GET/POST请求")

MyWebsite/templates/userprofile/edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    用户信息
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <div class="col-md-4">
                    用户名：{{ user.username }}
                </div>
                <br>
                {% if profile.avatar %}
                    <div class="col-md-4">头像</div>
                    <img src="{{ profile.avatar.url }}" style="max-width: 20%; border-radius: 15%;" class="col-md-4">
                {% else %}
                    <h5 class="col-md-4">暂无头像</h5>
                {% endif %}
                <br>
                <form action="." method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group col-md-4">
                        <label for="avatar">头像</label>
                        <input type="file" class="form-control-file" name="avatar" id="avatar">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="phone">电话</label>
                        <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                    </div>
                    <div class="form-group col-md-4">
                        <label for="bio">简介</label>
                        <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                    </div>

                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

MyWebsite/templates/userprofile/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    登录
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <h5>还没有帐号？</h5>
                <h5>点击<a href="{% url 'userprofile:register' %}">注册账号</a>加入我们吧！</h5>
                <br>
            </div>
            <div class="col-12">
                <br>
                <form action="." method="post">
                    {% csrf_token %}
                    {# 帐号 #}
                    <div class="form-group">
                        <label for="username">帐号</label>
                        <input type="text" class="form-control" id="username" name="username">
                    </div>
                    {# 密码 #}
                    <div class="form-group">
                        <label for="password">密码</label>
                        <input type="password" class="form-control" id="password" name="password">
                    </div>
                    {# 提交按钮 #}
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>

                <br>
                <h5>忘记密码？</h5>
                <h5>点击<a href="{% url 'password_reset_recover' %}">这里</a>重置密码</h5>
            </div>
        </div>
    </div>
{% endblock %}

MyWebsite/templates/userprofile/register.html
{% extends 'base.html' %}
{% block title %}
    登录
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form action="." method="post">
                    {% csrf_token %}
                    {# 帐号 #}
                    <div class="form-group col-md-4">
                        <label for="username">昵称</label>
                        <input type="text" class="form-control" id="username" name="username" required>
                    </div>
                    {# 邮箱 #}
                    <div class="form-group col-md-4">
                        <label for="email">Email</label>
                        <input type="text" class="form-control" id="email" name="email">
                    </div>
                    {# 密码 #}
                    <div class="form-group col-md-4">
                        <label for="password">设置密码</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                    {# 确认密码 #}
                    <div class="form-group col-md-4">
                        <label for="password2">确认密码</label>
                        <input type="password" class="form-control" id="password2" name="password2" required>
                    </div>
                    {# 提交按钮 #}
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}