MyWebsite/MyWebsite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include(('article.urls', 'article'), namespace='article')),
    path('userprofile/', include(('userprofile.urls', 'userprofile'), namespace='userprofile')),
    path('password-reset', include('password_reset.urls')),
    path('comment/', include(('comment.urls', 'comment'), namespace='comment')),
]

# 为上传的图片配置URL路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyWebsite/article/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.articled_create, name='article_create'),
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    # 安全删除文章
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

MyWebsite/comment/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # 发表评论
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
]

MyWebsite/userprofile/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('logout/', views.uesr_logout, name='logout'),
	path('register/', views.user_register, name='register'),
	path('delete/<int:id>/', views.user_delete, name='delete'),
	# 编辑用户信息
	path('edit/<int:id>/', views.profile_edit, name='edit'),
]

MyWebsite/article/models.py
from django.contrib.auth.models import User
from django.db import models

# 博客文章数据模型
from django.urls import reverse
from django.utils import timezone


class ArticlePost(models.Model):
    # 文章作者。参数 on_delete用于指定数据删除的方式
    author = models.ForeignKey(User, on_delete=models.PROTECT)

    # 文章标题。model.CharField为字符串字段，用于保存较短的字符串，例如标题
    title = models.CharField(max_length=100)

    # 文章正文。大文本用TextField
    body = models.TextField()

    # 文章浏览量，默认从0开始,PositiveIntegerField表示正整数
    total_views = models.PositiveIntegerField(default=0)

    # 文章创建时间。default=timezone.now指定在其创建数据时默认写入当前时间
    created = models.DateTimeField(default=timezone.now)

    # 文章更新时间。auto_now=True指定每次数据更新时自动写入当前时间
    updated = models.DateTimeField(auto_now=True)

    # 内部类 class Meta 用于给model定义元数据
    class Meta:
        # ordering指定模型返回的数据的排列顺序
        # '-created' 表明数据以创建时间倒序排序
        ordering = ('-created',)
        # 修改数据库表名
        db_table = 'ArticleData'

    # 函数__str__定义当调用对象的str()方法时的返回值内容
    def __str__(self):
        # 返回文章标题
        return self.title

    # 获取文章地址
    def get_absolute_url(self):
        # reverse:url反转，动态生成url
        # kwargs可以传递字典形式的参数
        return reverse('article:article_detail', args=[self.id])

MyWebsite/article/forms.py
from django import forms

from article.models import ArticlePost


# 写文章的表单类
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义数据模型字段
        fields = ('title', 'body')

MyWebsite/article/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
import markdown

from article.forms import ArticlePostForm
from article.models import ArticlePost
from comment.models import Comment


def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')

    if search:
        # 根据GET请求中的查询条件，返回不同排序的对象数组
        if order == 'total_views':
            article_lists = ArticlePost.objects.filter(Q(title__icontains=search) | Q(body__icontains=search)) \
                .order_by('-total_views')
        else:
            # 取出所有博客文章(默认排序)
            article_lists = ArticlePost.objects.filter(Q(title__icontains=search) | Q(body__icontains=search))
    else:
        # 将search参数置空
        search = ''
        if order == 'total_views':
            article_lists = ArticlePost.objects.all().order_by('-total_views')
        else:
            article_lists = ArticlePost.objects.all()
    # 每页显示3篇文章
    paginator = Paginator(article_lists, 3)
    # 获取url中的页码(通过GET的键值对参数请求:?key=value)
    page = request.GET.get('page')
    # 将导航对象相应的页码内容返回给article
    articles = paginator.get_page(page)
    # 需要传递给模板的对象
    context = {
        'articles': articles,
        'order': order,
        'search': search,
    }
    return render(request, 'article/list.html', context=context)


# 文章详情
def article_detail(request, id):
    # 取出相应的文章
    article = ArticlePost.objects.get(id=id)

    # 浏览量+1
    article.total_views += 1
    # 保存使用参数，只更新指定字段。
    # 不带参数的话，会更新全部字段，包括更新时间字段（导致该字段内容错误）
    article.save(update_fields=['total_views'])
    # article.save()

    # 取出文章评论
    comments = Comment.objects.filter(article=id)

    # 将markdown语法渲染成html样式
    # 欠缺：代码没有行号
    md = markdown.Markdown(
        extensions=[
            # 包含 缩写、表格等常用扩展
            'markdown.extensions.extra',
            # 语法高亮扩展
            'markdown.extensions.codehilite',
            # 目录扩展(需要加入标记[TOC])
            'markdown.extensions.toc',
        ]
    )
    article.body = md.convert(article.body)

    # 需要传递给模板的对象
    context = {
        'article': article,
        'toc': md.toc,
        'comments':comments,
    }
    # 载入模板，并返回context对象
    return render(request, 'article/detail.html', context)


# 写文章的视图
# 检查登录
@login_required(login_url='/userprofile/login/')
def articled_create(request):
    # 判断用户是否提交数据
    if request.method == 'POST':
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_article = article_post_form.save(commit=False)
            # 指定作者为当前登录用户
            new_article.author = User.objects.get(id=request.user.id)
            # 将新文章保存在数据库中
            new_article.save()
            # 完成后返回文章列表
            return redirect('article:article_list')
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse('表单内容有误，请重新填写！！！')

    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文
        context = {
            'article_post_form': article_post_form,
        }
        return render(request, 'article/create.html', context)


# 删文章，需要对用户进行身份验证（未进行）
@login_required(login_url='/userprofile/login')
def article_delete(request, id):
    # 根据id获取需要删除的文章
    article = ArticlePost.objects.get(id=id)
    # 调用delete方法删除文章
    article.delete()
    return redirect('article:article_list')


# 安全删除文章（只允许POST请求），需要对用户进行身份验证（未进行）
@login_required(login_url='/userprofile/login')
def article_safe_delete(request, id):
    article = ArticlePost.objects.get(id=id)
    # 过滤非法用户
    if request.user != article.author:
        return HttpResponse('很抱歉，您无权删除本文章')
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        article.delete()
        return redirect('article:article_list')
    else:
        return HttpResponse('非法请求！')


# 更新文章
@login_required(login_url='/userprofile/login')
def article_update(request, id):
    """
    更新文章的视图函数
    通过POST方法提交表单，更新title、body字段
    GET方法进入初始表单页面
    :param request:
    :param id: 文章的id
    :return:
    """
    # 获取需要修改的具体文章的对象
    article = ArticlePost.objects.get(id=id)

    # 过滤非法用户
    if request.user != article.author:
        return HttpResponse('很抱歉，您无权修改本文章')
    # 判断用户是否为POST提交表单数据
    if request.method == 'POST':
        # 将提交的数据赋值到表单实例中
        '''
        另一种方法：
        article_post_form = ArticlePostForm(data=request.POST, instance=article)
        if article_post_form.is_valid():
            article_post_form.save()
        '''
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存新写入的title、body数据并保存
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            # 完成后返回到修改的文章中，需传入文章的id值
            return redirect('article:article_detail', id=id)
        # 数据不合法，返回错误信息
        else:
            return HttpResponse('表单信息有误，请重新填写')

    # 如果用户GET请求获取数据
    else:
        # 创建表单实例
        article_post_form = ArticlePostForm()
        # 赋值上下文，将article文章对象也传递进去，以便提取旧的内容
        context = {
            'article': article,
            'article_post_form': article_post_form,
        }
        return render(request, 'article/update.html', context)

MyWebsite/templates/article/create.html
{% extends 'base.html' %}
{% block title %}
    写文章
{% endblock %}

{% block content %}
    {# 写文章表单 #}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                {# 提交文章的表单 action="."指定了表单提交的地址为默认的当前url #}
                <form action="." method="post">
                    {# Django需要POST数据的地方都必须有csrf_token #}
                    {% csrf_token %}
                    {# 文章标题 #}
                    <div class="form-group">
                        {# 标签 #}
                        <label for="title">文章标题</label>
                        {# 文本框 #}
                        <input type="text" class="form-control" id="title" name="title">
                    </div>
                    {# 文章正文 #}
                    <div class="form-group">
                        <label for="body">文章正文</label>
                        {# 文本区域 #}
                        <textarea name="body" id="body" type="text" class="form-control"></textarea>
                    </div>
                    {# 提交按钮 #}
                    <button type="submit" class="btn btn-primary">完成</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

MyWebsite/templates/article/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    文章详情
{% endblock %}

{% block content %}
    {# 文章详情 #}
    <div class="container">
        <div class="row">
            <div class="col-9">
                {# 标题及作者 #}
                <h1 class="col-12 mt-4 mb-4">
                    {{ article.title }}
                </h1>
                <div class="col-12 alert alert-success">
                    <div>
                        作者：{{ article.author }}
                        {% if user == article.author %}
                            · <a href="#" onclick="confirm_safe_delete()">删除文章</a>
                            · <a href="{% url 'article:article_update' article.id %}">编辑文章</a>
                        {% endif %}
                    </div>
                </div>
                <div>
                    浏览：{{ article.total_views }}
                </div>
                {# 使用隐藏form表单提交删除等敏感操作，用csrf令牌防范csrf攻击 #}
                <form
                        action="{% url 'article:article_safe_delete' article.id %}"
                        id="safe_delete"
                        style="display: none"
                        method="POST"
                >
                    {% csrf_token %}
                    <button type="submit">发送</button>
                </form>

                {# 文章正文 #}
                <div class="col-12">
                    <p>{# 这里要确认安全才能这样写，不然可以注入 #}
                        {{ article.body|safe }}
                    </p>
                </div>
                {# 发表评论 #}
                <hr>
                {% if user.is_authenticated %}
                    <div>
                        <form action="{% url 'comment:post_comment' article.id %}" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="body">
                                    <strong>我也要发言：</strong>
                                </label>
                                <textarea name="body" id="body" rows="2" type="text" class="form-control"></textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">发送</button>
                        </form>
                    </div>
                {% else %}
                    <br>
                    <h5 class="row justify-content-center">
                        请<a href="{% url 'userprofile:login' %}">登录</a>后回复
                    </h5>
                {% endif %}

                {# 显示评论 #}
                <br>
                <h4>共有{{ comments.count }}条评论</h4>
                <div>
                    {% for comment in comments %}
                        <hr>
                        <p>
                            <strong style="color: pink;">
                                {{ comment.user }}
                            </strong> 于
                            <span style="color: green;">
                                {{ comment.created|date:"Y-m-d H:i:s" }}
                            </span> 时说：
                        </p>
                        {# pre定义预格式化的文本，常用于保留空格和换行符等 #}
                        <pre style="font-family: inherit; font-size: 1em;">{{ comment.body }}</pre>
                    {% endfor %}
                </div>
            </div>
            {# 目录 #}
            <div class="col-3 mt-4">
                <h4><strong>目录</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>
    </div>

    <script>
        //删除文章的函数
        function confirm_delete() {
            //调用layer弹窗组件
            layer.open({
                //弹窗标题
                title: '确认删除',
                //正文
                content: '确认删除这篇文章吗？',
                //点击确定按钮后调用的回调函数
                yes: function (index, layero) {
                    //指定应当前往的url
                    location.href = "{% url 'article:article_delete' article.id %}"
                }
            })
        }

        //安全（使用表单post提交删除）删除文章的函数
        function confirm_safe_delete() {
            //调用layer弹窗组件
            layer.open({
                //弹窗标题
                title: '确认删除',
                //正文
                content: '确认删除这篇文章吗？',
                //点击确定按钮后调用的回调函数
                yes: function (index, layero) {
                    $('form#safe_delete button').click();
                    layer.close(index);
                }
            })
        }
    </script>
{% endblock %}

MyWebsite/templates/article/list.html
{# extends继承base.html #}
{% extends 'base.html' %}
{% load static %}

{# 写入base定义的title #}
{% block title %}
    首页
{% endblock %}

{# 写入base定义的content #}
{% block content %}
    {# 定义放置文章标题的div容器 #}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'article:article_list' %}?search={{ search }}">
                        最新
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'article:article_list' %}?order=total_views&search={{ search }}">
                        最热
                    </a>
                </li>
            </ol>
        </nav>
        {# 搜索栏 #}
        <div class="row">
            <div class="col-auto mr-auto">
                <form action="" class="form-inline">
                    <label for="" class="sr-only">content</label>
                    <input type="text" class="form-control mb-2 mr-sm-2" name="search" placeholder="搜索文章..." required>
                </form>
            </div>
        </div>
        {# 搜索提示语 #}
        {% if search %}
            {% if articles %}
                <h4><span style="color: red;">"{{ search }}"</span>的搜索结果如下：</h4>
                <hr>
            {% else %}
                <h4>暂无与<span style="color: red;">"{{ search }}"</span>有关的文章。</h4>
                <hr>
            {% endif %}
        {% endif %}
        <div class="row mt-2">
            {% for article in articles %}
                {# 文章内容 #}
                <div class="col-4 mb-4">
                    {# 卡片容器 #}
                    <div class="card h-100">
                        {# 标题 #}
                        <h4 class="card-header">
                            {{ article.title }}
                        </h4>
                        {# 摘要 #}
                        <div class="card-body">
                            <p class="card-text">
                                {{ article.body|slice:'100' }}...
                            </p>
                        </div>
                        {# 注脚 #}
                        <div class="card-footer">
                            <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
                        </div>
                        {# 浏览量 #}
                        <span>
                            <small class="col align-self-end" style="color: gray;">
                                浏览：{{ article.total_views }}
                            </small>
                        </span>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
    {# 页码 #}
    <div class="pagination row">
        <div class="m-auto">
            <span class="step-links">
                {# 不是第一页则显示上翻 #}
                {% if articles.has_previous %}
                    <a href="?page=1&order={{ order }}&search={{ search }}" class="btn btn-success">
                        &laquo; 1
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}" class="btn btn-secondary">
                        {{ articles.previous_page_number }}
                    </a>
                {% endif %}
                {# 当前页面 #}
                <span class="current btn btn-danger btn-lg">
                    {{ articles.number }}
                </span>
                {# 不是末页则显示下翻 #}
                {% if articles.has_next %}
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}" class="btn btn-secondary">
                        {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}" class="btn btn-success">
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>
{% endblock %}

MyWebsite/templates/article/update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    更新文章
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <br>
                <form action="." method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="title">文章标题</label>
                        {# 在value属性中指定文本框的初始值为旧的内容 #}
                        <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                    </div>
                    <div class="form-group">
                        <label for="body">文章正文</label>
                        {# 文本域不需要Value模型，直接在标签提中嵌入数据即可 #}
                        <textarea name="body" id="body" type="text" class="form-control" rows="12">{{ article.body }}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">完成</button>
                    <a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">返回</a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}