MyWebsite/MyWebsite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include(('article.urls', 'article'), namespace='article')),
    path('userprofile/', include(('userprofile.urls', 'userprofile'), namespace='userprofile')),
    path('password-reset', include('password_reset.urls')),
    path('comment/', include(('comment.urls', 'comment'), namespace='comment')),
]

# 为上传的图片配置URL路径
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyWebsite/article/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('article-list/', views.article_list, name='article_list'),
    # 文章详情
    path('article/<int:id>/', views.article_detail, name='article_detail'),
    path('article-create/', views.articled_create, name='article_create'),
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    # 安全删除文章
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    path('article-update/<int:id>/', views.article_update, name='article_update'),
]

MyWebsite/userprofile/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('logout/', views.uesr_logout, name='logout'),
	path('register/', views.user_register, name='register'),
	path('delete/<int:id>/', views.user_delete, name='delete'),
	# 编辑用户信息
	path('edit/<int:id>/', views.profile_edit, name='edit'),
]

MyWebsite/templates/base.html
{#载入静态文件#}
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
    {# 引入bootstrap的css文件 #}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    {# 引入代码高亮monikai.css #}
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
</head>
<body>
    {# 引入导航栏 #}
    {% include 'header.html' %}
    {# 预留具体页面的位置 #}
    {% block content %}

    {% endblock %}
    {# 引入注脚 #}
    {% include 'footer.html' %}
    {# bootstrap.js依赖jq.js和popper.js #}
    <script src="{% static 'jquery/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'popper/popper.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    {# 引入layer.js以来jq.js #}
    <script src="{% static 'layer/layer.js' %}"></script>
</body>
</html>

MyWebsite/templates/footer.html
{% load static %}
{# Footer #}
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">
            Copyright &copy; blog.PurpleSword.art 2020
        </p>
    </div>
</footer>

MyWebsite/templates/header.html
{# 定义导航栏 #}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        {# 导航栏商标 #}
        <a class="navbar-brand" href="#">我的博客</a>

        {# 导航入口 #}
        <div>
            <ul class="navbar-nav">
                {# 条目 #}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
                </li>
                {# Django的if模板语句 is_authenticated是models.User类的属性，用于判断用户是否已通过身份验证 #}
                {% if user.is_authenticated %}
                    {# 如果用户已经登录，则显示用户名下拉框 #}
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a href="{% url 'userprofile:edit' user.id %}" class="dropdown-item">个人信息</a>
                            <a href="{% url 'article:article_create' %}" class="dropdown-item">写文章</a>
                            <a href="{% url 'userprofile:logout' %}" class="dropdown-item">退出登录</a>
                            <a href="#" onclick="user_delete()" class="dropdown-item">删除用户</a>
                        </div>
                    </li>
                    {# 如果用户未登录，显示“登录” #}
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'userprofile:login' %}" class="nav-link">登录</a>
                    </li>
                {% endif %}

                {# 用户未登录时是没有user.id属性的，但函数中使用了，包裹在if语句中 #}
                {# 保证了只有在用户登录的情况下才对这些代码进行解析 #}
                {% if user.is_authenticated %}
                    <form
                            action="{% url 'userprofile:delete' user.id %}"
                            style="display: none;"
                            id="user_delete"
                            method="post"
                    >
                        {% csrf_token %}
                        <button type="submit">发送</button>
                    </form>
                    <script>
                        function user_delete() {
                            //调用layer弹窗组件
                            layer.open({
                                title: '确认删除',
                                content: '确认删除用户资料吗？',
                                yes: function (index, layero) {
                                    $('form#user_delete button').click();
                                    layer.close(index)
                                },
                            })
                        }
                    </script>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>